use_frameworks!

target 'XiaoDeKit-Example' do
  
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'XiaoDeKit-Swift', :path => '../'

  target 'XiaoDeKitTests' do
    inherit! :search_paths
  end

end
